
[settings]
	#Enable debug mode (Developers only) WARNING! Will override all horse names!
	enableDebug = false
	#Personal Horses get deleted if they're killed
	deathIsPermanent = true
	#If the horse can be called in every dimension
	callableInEveryDimension = true
	#Whitelist for dimensions where horses can be called. callableInEveryDimension needs to be false!
	callableDimsWhitelist = ["minecraft:overworld"]
	#Maximum block distance from last horse where new horse can be called. Set to -1 to disable range.
	#Range: -1 ~ 30000000
	maxCallingDistance = -1
	#Enable/disable the horse stat viewer GUI
	enableStatsViewer = false
	#Range in which the horse will not teleport, but walk to you. Set to 0 to force the horse to always teleport.
	#Range: 0.0 ~ 64.0
	horseWalkRange = 32.0
	#Speed with which the horse walks when you call it. Vanilla horse walk speed is 1.2
	#Range: 0.0 ~ 10.0
	horseWalkSpeed = 1.8
	#Check against duplicate horses every game tick (20 times per second) instead of only on load. Only use this if you're experiencing problem with duplicate horses! THIS COULD CAUSE LAG!
	continuousAntiDupeChecking = false
	#Prevents personal horses from dropping items (like leather). This won't prevent armor or saddles from dropping. If this is disabled in combination with deathIsPermanent, it can become a really easy way to farm/duplicate leather, so keep that in mind.
	disableHorseDrops = true
	#If you need a 3x3x3 space to call your horse
	checkForSpace = true

