#The dimension from where you can teleport to the mining dimension and back
overworld_dimension = "minecraft:overworld"
#If the teleporter should bring you to the lowest free space in the mining dimension
spawn_deep = true

