
#Dungeon Configs
[general]
	#Range: 0 ~ 100000
	TOWER_SEPARATION = 10
	#Range: 0 ~ 1000
	TOWER_SPACING = 40
	#Range: > 0
	TOWER_SEED = 270951955
	AUTO_DESTROY_TOWERS = false
	ALLOWED_MOBS_FOR_SPAWNERS = ["minecraft:zombie", "minecraft:zombie_villager", "minecraft:skeleton", "minecraft:stray", "minecraft:husk", "minecraft:witch"]
	ALLOWED_BOSSES = ["minecraft:wither_skeleton", "minecraft:iron_golem", "minecraft:ravager", "minecraft:evoker", "minecraft:illusionist"]

