
#Vanilla Trees Settings
[vanilla]
	#Right clicking with a vanilla sapling places a dynamic sapling instead.
	replaceVanillaSapling = false
	#Crimson Fungus and Warped Fungus that sprout from nylium will be dynamic instead.
	replaceNyliumFungi = true

#World Generation Settings
[world]
	#World Generation produces Dynamic Trees instead of Vanilla trees.
	worldGen = true
	#Blacklist of dimension registry names for disabling Dynamic Tree worldgen (tree cancellers need to be configured individually for biomes in dynamictrees/tree_canceller.json)
	dimensionsBlacklist = []

#Mod Integration Settings
[integration]
	#The mod ID of preferred season mod. If a season provider for this mod ID is present, it will be used for integration with seasons. Set this to "!" to disable integration or "*" to accept the any integration (the first available).
	preferredSeasonMod = "*"
	#If enabled, seed drop rates will be multiplied based on the current season (requires serene seasons).
	enableSeasonalSeedDropFactor = true
	#If enabled, growth rates will be multiplied based on the current season (requires serene seasons).
	enableSeasonalGrowthFactor = true
	#If enabled, fruit production rates will be multiplied based on the current season (requires serene seasons).
	enableSeasonalFruitProductionFactor = true

