
[custom_weaponry]

	[custom_weaponry.sample]
		registry_name = "modid:registryname"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.5
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.woodstaff]
		registry_name = "mmorpg:weapon/staff/wood"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.5
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.ironstaff]
		registry_name = "mmorpg:weapon/staff/iron"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.goldstaff]
		registry_name = "mmorpg:weapon/staff/gold"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.9
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.diamondstaff]
		registry_name = "mmorpg:weapon/staff/diamond"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 1.1
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.neptuniumbow]
		registry_name = "aquaculture:neptunium_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.iron_dagger]
		registry_name = "atum:iron_dagger"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.2
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.daggerpoison]
		registry_name = "atum:dagger_poison"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.3
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.shortbow]
		registry_name = "atum:shortbow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.anputs_grounding]
		registry_name = "atum:anputs_grounding"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.gebs_might]
		registry_name = "atum:gebs_might"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.4
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.horus_soaring]
		registry_name = "atum:horus_soaring"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.isis_division]
		registry_name = "atum:isis_division"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.montus_blast]
		registry_name = "atum:montus_blast"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.ras_fury]
		registry_name = "atum:ras_fury"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.seths_venom]
		registry_name = "atum:seths_venom"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.shus_breath]
		registry_name = "atum:shus_breath"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.tefnets_rain]
		registry_name = "atum:tefnets_rain"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.tefnets_call]
		registry_name = "atum:tefnets_call"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "TRIDENT"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.iron_hammer]
		registry_name = "betterendforge:iron_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.2
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.gold_hammer]
		registry_name = "betterendforge:gold_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.diamond_hammer]
		registry_name = "betterendforge:diamond_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.4
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.netherite_hammer]
		registry_name = "betterendforge:netherite_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.6
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.thallasium_hammer]
		registry_name = "betterendforge:thallasium_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.8
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.terminite_hammer]
		registry_name = "betterendforge:terminite_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 3.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.aeternium_hammer]
		registry_name = "betterendforge:aeternium_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 3.2
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.livingwood]
		registry_name = "botania:livingwood_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.crystalbow]
		registry_name = "botania:crystal_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.crushinghammer]
		registry_name = "blue_skies:crushing_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.8
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.soulbound_spear]
		registry_name = "blue_skies:soulbound_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 2.8
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.maple_spear]
		registry_name = "blue_skies:maple_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 2.5
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.cherry_spear]
		registry_name = "blue_skies:cherry_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 2.5
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.frostbright_spear]
		registry_name = "blue_skies:frostbright_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 2.5
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.bluebright_spear]
		registry_name = "blue_skies:bluebright_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 3.0
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.dusk_spear]
		registry_name = "blue_skies:dusk_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 3.0
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.lunar_spear]
		registry_name = "blue_skies:lunar_spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		impact = 3.0
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.overcharged_hammer]
		registry_name = "create:overcharged_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 3.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.dynamictreesstaff]
		registry_name = "dynamictrees:staff"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.flint_knife]
		registry_name = "farmersdelight:flint_knife"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.iron_knife]
		registry_name = "farmersdelight:iron_knife"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.2
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.gold_knife]
		registry_name = "farmersdelight:gold_knife"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.diamond_knife]
		registry_name = "farmersdelight:diamond_knife"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.3
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.netherite_knife]
		registry_name = "farmersdelight:netherite_knife"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.4
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.glowsilk_bow]
		registry_name = "infernalexp:glowsilk_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.pharaoscepter]
		registry_name = "minecolonies:pharaoscepter"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.mowziespear]
		registry_name = "mowziesmobs:spear"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 2.8
		armor_ignorance = 0.0
		hit_at_once = 2

	[custom_weaponry.mowziesnagadagger]
		registry_name = "mowziesmobs:naga_fang_dagger"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		impact = 1.3
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.arachnonhamer]
		registry_name = "pandoras_creatures:arachnon_hammer"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		impact = 2.8
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.wandoffreezing]
		registry_name = "savageandravage:wand_of_freezing"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.twilightscepter]
		registry_name = "twilightforest:twilight_scepter"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.lifedrainscepter]
		registry_name = "twilightforest:lifedrain_scepter"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.zombiescepter]
		registry_name = "twilightforest:zombie_scepter"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.shieldscepter]
		registry_name = "twilightforest:shield_scepter"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		impact = 0.7
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.tribow]
		registry_name = "twilightforest:triple_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.seeker_bow]
		registry_name = "twilightforest:seeker_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.ice_bow]
		registry_name = "twilightforest:ice_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

	[custom_weaponry.ender_bow]
		registry_name = "twilightforest:ender_bow"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "BOW"
		impact = 1.0
		armor_ignorance = 0.0
		hit_at_once = 1

[custom_armor]

	[custom_armor.sample]
		registry_name = "modid:registryname"
		weight = 0.0
		stun_armor = 0.0

[custom_entity]

	[custom_entity.sample]
		type_name = "modid:type_name"
		texture_location = "modid:texture_location"
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		impact = 0.5
		armor_negation = 0.0
		max_strikes = 1

