
#Client settings
[client]
	#Should the hunger bar have a gilded overlay when the player has the Nourishment effect?
	nourishmentHungerOverlay = true
	#Should food tooltips display which effects they provide?
	foodEffectTooltip = true

