
#Client Configs
[general]
	show_low_mana_warning = true
	render_mob_bar = true
	render_death_stats = true
	render_item_rarity_background = true
	show_durability = true
	render_mob_hp_gui = false
	only_render_mob_looked_at = false
	render_floating_damage = true

