
[music]
	#Minimum delay for next song to play
	#Range: > 0
	mindelay = 0
	#Maximum delay for next song to play
	#Range: > 0
	maxdelay = 30
	#Divide delays of length instead?
	divide = false
	#Division delay amount
	#Range: > 0
	division = 2

	[music.experimental]
		#Change pitch/key randomly each time a song starts
		distortPitch = false
		#The chance for a song to change pitch/key
		#Range: 0.0 ~ 1.0
		chanceToPitchChange = 0.3
		#Minimum key change (inclusive), Set lower for slower/lower music.
		#Range: -12 ~ 12
		minNoteChange = -12
		#Maximum key change (inclusive), Set higher for faster/higher music.
		#Range: -12 ~ 12
		maxNoteChange = 12

