
[Client]
	#Render centrifuge comb inventory on the block.
	renderCombsInCentrifuge = true
	#Render bees inside bee jars.
	renderBeesInJars = true
	#Render bees as entities in JEI and in hive GUI. Set to false to show an image of the bee instead.
	renderBeeIngredientAsEntity = true

