
[structures]

	[structures.global]
		#How flat does terrain need to be for surface structures to spawn? (in blocks) [default: 4]
		#Range: 0 ~ 64
		flatness_delta = 4
		#Dimensions in which Structures can NOT generate in
		blacklisted_dimensions = ["the_bumblezone:the_bumblezone", "twilightforest:twilightforest", "mmorpg:dungeon", "mining_dimension:mining", "dimdungeons:dungeon_dimension"]
		#Biomes in which Structures can NOT generate in
		blacklisted_biomes = ["minecraft:ocean", "minecraft:river", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:beach", "minecraft:deep_ocean", "minecraft:snowy_beach", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean"]

	[structures.castle]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.5]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.25
		#Spacing (in chunks) [default: 40]
		#Range: 0 ~ 200
		spacing = 80
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "taiga"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.castle_ruin]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.3
		#Spacing (in chunks) [default: 35]
		#Range: 0 ~ 200
		spacing = 70
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "taiga"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.desert_house]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.35
		#Spacing (in chunks) [default: 30]
		#Range: 0 ~ 200
		spacing = 60
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["desert"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.forge]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.14
		#Spacing (in chunks) [default: 30]
		#Range: 0 ~ 200
		spacing = 60
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "extreme_hills", "taiga"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.player_house]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.35
		#Spacing (in chunks) [default: 30]
		#Range: 0 ~ 200
		spacing = 60
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "extreme_hills", "taiga"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.spawner_dungeon]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.35
		#Spacing (in chunks) [default: 30]
		#Range: 0 ~ 200
		spacing = 60
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "extreme_hills", "taiga", "desert", "mesa", "savanna", "jungle", "icy", "swamp", "mushroom"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.tower_ruin]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.8]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.4
		#Spacing (in chunks) [default: 25]
		#Range: 0 ~ 200
		spacing = 50
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 8
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest", "extreme_hills", "taiga"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.witch_hut]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.85]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.4
		#Spacing (in chunks) [default: 25]
		#Range: 0 ~ 200
		spacing = 50
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["swamp"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

	[structures.big_tree]
		#Generate? [default: true]
		generate = true
		#Spawn Chance [default: 0.7]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.25
		#Spacing (in chunks) [default: 30]
		#Range: 0 ~ 200
		spacing = 90
		#Minimum Separation (in chunks) [default: 8]
		#Range: 0 ~ 200
		separation = 16
		#Biome Categories the structure can generate in 
		#Allowed Values: [none, taiga, extreme_hills, jungle, mesa, plains, savanna, icy, theend, beach, forest, ocean, desert, river, swamp, mushroom, nether]
		biome_categories = ["plains", "forest"]
		#Dimensions the structure can NOT generate in
		blacklisted_dimensions = []
		#Biomes the structure can NOT generate in
		blacklisted_biomes = []

